# Generated by Django 3.0.1 on 2020-05-06 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cheese', models.BooleanField(default=False, verbose_name='Extra Cheese')),
                ('onion', models.BooleanField(default=False, verbose_name='Extra onion')),
                ('tomato', models.BooleanField(default=False, verbose_name='Extra tomato')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('image_url', models.CharField(blank=True, max_length=2083)),
                ('pizza', models.OneToOneField(default=False, on_delete=django.db.models.deletion.CASCADE, to='pizza.Pizza')),
            ],
        ),
    ]
